/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;
import javax.swing.JOptionPane;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author user
 */
public class CetakLaporan extends javax.swing.JFrame {

    /**
     * Creates new form CetakLaporan
     */
    public CetakLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnlaporanbarang = new javax.swing.JButton();
        btnlaporanuser = new javax.swing.JButton();
        btnkembalikeuser = new javax.swing.JButton();
        btnkembalikebrg = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnkembalikemainmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cetak Laporan user");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setText("Cetak Laporan Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnlaporanbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Distributor-report-icon 32x32.png"))); // NOI18N
        btnlaporanbarang.setText("Cetak laporan");
        btnlaporanbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanbarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnlaporanbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        btnlaporanuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Distributor-report-icon 32x32.png"))); // NOI18N
        btnlaporanuser.setText("Cetak laporan");
        btnlaporanuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanuserActionPerformed(evt);
            }
        });
        getContentPane().add(btnlaporanuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        btnkembalikeuser.setText("Kembali Ke form User");
        btnkembalikeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembalikeuserActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembalikeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btnkembalikebrg.setText("Kembali ke form Barang");
        btnkembalikebrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembalikebrgActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembalikebrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        btnkembalikemainmenu.setText("Kembali Ke mainmenu");
        btnkembalikemainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembalikemainmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembalikemainmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlaporanbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanbarangActionPerformed
    JasperReport jr; 
    JasperPrint jp;
    JasperDesign jd;
    try{
        
        //panggil class koneksi
        java.sql.Connection conn =(Connection)koneksi.configDB();
        HashMap parameter=new HashMap();
        
        File report =new File("src/Laporan/LaporanBarang.jrxml");
        jd=JRXmlLoader.load(report);
        jr=JasperCompileManager.compileReport(jd);
        jp=JasperFillManager.fillReport(jr,parameter,conn);
        JasperViewer.viewReport(jp,false);     
    } catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    }//GEN-LAST:event_btnlaporanbarangActionPerformed

    private void btnlaporanuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanuserActionPerformed
    JasperReport jr; 
    JasperPrint jp;
    JasperDesign jd;
    try{
        
        //panggil class koneksi
        java.sql.Connection conn =(Connection)koneksi.configDB();
        HashMap parameter=new HashMap();
        
        File report =new File("src/Laporan/LaporanUser.jrxml");
        jd=JRXmlLoader.load(report);
        jr=JasperCompileManager.compileReport(jd);
        jp=JasperFillManager.fillReport(jr,parameter,conn);
        JasperViewer.viewReport(jp,false);     
    } catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    }//GEN-LAST:event_btnlaporanuserActionPerformed

    private void btnkembalikebrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembalikebrgActionPerformed
     new Form_Barang().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnkembalikebrgActionPerformed

    private void btnkembalikemainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembalikemainmenuActionPerformed
     new menuutama().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnkembalikemainmenuActionPerformed

    private void btnkembalikeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembalikeuserActionPerformed
     new Form_User().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnkembalikeuserActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CetakLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CetakLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CetakLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CetakLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CetakLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnkembalikebrg;
    private javax.swing.JButton btnkembalikemainmenu;
    private javax.swing.JButton btnkembalikeuser;
    private javax.swing.JButton btnlaporanbarang;
    private javax.swing.JButton btnlaporanuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
