/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hadip
 */
public class Form_Barang extends javax.swing.JFrame {
    
    private void kosongkan_form(){
        txtkd.setText(null);
        txtnama.setText(null);
        cbsatuan.setSelectedIndex(0);
        txtharga.setText(null);
        txtstok.setText(null);
    }
    
    private void tampilkan_data(){
        //membuat judul kolom pada TablePenjualan
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Satuan");
        model.addColumn("Harga");
        model.addColumn("Stok");
        
        String cari = txtcari.getText();
        try{
            int no=1;
            String sql ="SELECT * FROM barang WHERE kd_barang LIKE '%"+cari+"%'";
            //panggil class koneksi
            java.sql.Connection con = (Connection)koneksi.configDB();
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()){
                model.addRow(new Object[]{no++,res.getString(1),
                    res.getString(2),res.getString(3),res.getString(4),
                    res.getString(5)});
                tabelbarang.setModel(model);
            }
        }catch (SQLException e){
            System.out.println("Error :"+e.getMessage());
        }
    }

    /**
     * Creates new form Form_Barang
     */
    public Form_Barang() {
        initComponents();
        tampilkan_data();
        //non aktifkan tombol edit dan hapus
        btnubah.setEnabled(false);
        btnhapus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtkd = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbsatuan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        btnkeluar = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        kembalikeMainMenu2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/002-groceries.png"))); // NOI18N
        jLabel1.setText("Manajemen Data Barang");
        jLabel1.setMaximumSize(new java.awt.Dimension(654, 512));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        jLabel2.setText("Stok");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 160, -1));

        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setText("Kode Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtkd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkdKeyReleased(evt);
            }
        });
        getContentPane().add(txtkd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 160, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 150, -1));

        jLabel5.setText("Cari Data");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        cbsatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...Pilih...", "Gram", "Mili", "Pcs", "Lusin", "Pack", "Dus", "Kilogram" }));
        getContentPane().add(cbsatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jLabel6.setText("Satuan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel7.setText("Harga");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, -1));
        getContentPane().add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 160, -1));

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 910, 360));

        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Actions-window-close-icon 32x32.png"))); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, -1, -1));

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Editing-Delete-icon 32x32.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, -1, -1));

        btnubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Text-Edit-icon 32x32.png"))); // NOI18N
        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, -1, -1));

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sign-Refresh-icon 32x32.png"))); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, -1, -1));

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Save-as-icon 32x32.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, -1, -1));

        kembalikeMainMenu2.setText("Kembali ke Mainmenu");
        kembalikeMainMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalikeMainMenu2ActionPerformed(evt);
            }
        });
        getContentPane().add(kembalikeMainMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(menuutama.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void txtkdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkdKeyReleased
        // TODO add your handling code here:
        String input = txtkd.getText();
        if (input.length()>8){
            JOptionPane.showMessageDialog(rootPane,"Jumlah Input ID Order Melebihi Batas");
            txtkd.setText("");
        }
    }//GEN-LAST:event_txtkdKeyReleased

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="INSERT INTO barang VALUES('"+txtkd.getText()+"','"
                    +txtnama.getText()+"','"
                    +cbsatuan.getSelectedItem()+"','"
                    +txtharga.getText()+"','"
                    +txtstok.getText()+"')";
            java.sql.Connection con = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();
            
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil");
            
            tampilkan_data();
            kosongkan_form();
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        //Panggil Method KosongkanForm
        kosongkan_form();
        //aktifkan tombol simpan
        btnsimpan.setEnabled(true);
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="UPDATE barang SET nama_barang='"+txtnama.getText()
                    +"',satuan ='"+cbsatuan.getSelectedItem()
                    +"',harga='"+txtharga.getText()
                    +"',stok='"+txtstok.getText()
                    +"'WHERE kd_barang='"+txtkd.getText()+"'";
            java.sql.Connection con = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();
            
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
            
            tampilkan_data();
            kosongkan_form();
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        btnsimpan.setEnabled(true);
        btnubah.setEnabled(false);
        btnhapus.setEnabled(false);
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try{
            String sql="DELETE FROM barang WHERE kd_barang='"+txtkd.getText()+"'";
            java.sql.Connection con=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Telah di Hapus...!");
            tampilkan_data();
            kosongkan_form();
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        btnsimpan.setEnabled(true);
        btnubah.setEnabled(false);
        btnhapus.setEnabled(false);
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        int pilihan =JOptionPane.showConfirmDialog(null,
                "Apakah Anda ingin keluar dari program ?",
                "Title Keluar:",JOptionPane.YES_NO_OPTION);
        if (pilihan==JOptionPane.YES_OPTION)
            this.dispose();
        else
            txtkd.requestFocus();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, 
             "Silahkan data diperbaharui terlebih dahulu \n Lakukan dengan benar \n",
             "Perbaharui Data !",JOptionPane.PLAIN_MESSAGE);
             btnsimpan.setEnabled(false);
             btnubah.setEnabled(true);
             btnhapus.setEnabled(true);
        int baris =tabelbarang.rowAtPoint(evt.getPoint());
        String kd_barang =tabelbarang.getValueAt(baris, 1).toString();
        txtkd.setText(kd_barang);
        String nama_barang=tabelbarang.getValueAt(baris, 2).toString();
        txtnama.setText(nama_barang);
        String satuan=tabelbarang.getValueAt(baris, 3).toString();
        cbsatuan.setSelectedItem(satuan);
        String harga=tabelbarang.getValueAt(baris, 4).toString();
        txtharga.setText(harga);
        String stok=tabelbarang.getValueAt(baris, 5).toString();
        txtstok.setText(stok);
    }//GEN-LAST:event_tabelbarangMouseClicked

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
        tampilkan_data();
    }//GEN-LAST:event_txtcariKeyReleased

    private void kembalikeMainMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalikeMainMenu2ActionPerformed
        new menuutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembalikeMainMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbsatuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembalikeMainMenu;
    private javax.swing.JButton kembalikeMainMenu1;
    private javax.swing.JButton kembalikeMainMenu2;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkd;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
