/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author hadip
 */
public class Form_User extends javax.swing.JFrame {
    
    private void kosongkan_form(){
        txtid.setText(null);
        txtnama.setText(null);
        txtalamat.setText(null);
        txttlp.setText(null);
        cbstatus.setSelectedIndex(0);
        txtuser.setText(null);
        txtpw.setText(null);
        txtacc.setText(null);
    }
    private void tampilkan_data(){
        //membuat judul kolom pada TablePenjualan
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("Id User");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        model.addColumn("Status");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Akses");
        
        //variabel cari untuk proses pencarian data pada txtcaridata
        String cari = txtcari.getText();
        try{
            int no=1;
            String sql ="SELECT * FROM user WHERE id_user LIKE '%"+cari+"%'";
            //panggil class koneksi
            java.sql.Connection con = (Connection)koneksi.configDB();
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()){
                model.addRow(new Object[]{no++,res.getString(1),
                    res.getString(2),res.getString(3),res.getString(4),
                    res.getString(5),res.getString(6),res.getString(7),
                    res.getString(8)});
                tabeluser.setModel(model);
            }
        }catch (SQLException e){
            //tampilkan pesan di sistem kalau terjadi error
            System.out.println("Error :"+e.getMessage());
        }
    }

    /**
     * Creates new form Form_User
     */
    public Form_User() {
        initComponents();
        tampilkan_data();
        //non aktifkan tombol edit dan hapus
        btnubah.setEnabled(false);
        btnhapus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttlp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpw = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbstatus = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtacc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeluser = new javax.swing.JTable();
        btnkeluar = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/user.png"))); // NOI18N
        jLabel1.setText("Manajemen User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("Cari Data");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 190, 30));

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel5.setText("Id User");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 130, -1));
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 250, 30));

        jLabel6.setText("Telpon");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));
        getContentPane().add(txttlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 130, -1));

        jLabel7.setText("Akses");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 160, -1));

        jLabel8.setText("Username");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));
        getContentPane().add(txtpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 160, -1));

        jLabel9.setText("Status");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...Pilih...", "Aktif", "Tidak Aktif" }));
        cbstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstatusActionPerformed(evt);
            }
        });
        getContentPane().add(cbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel10.setText("Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));
        getContentPane().add(txtacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 160, -1));

        jLabel11.setText("Tabel Data User");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        tabeluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeluserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeluser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 880, 260));

        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Actions-window-close-icon 32x32.png"))); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Editing-Delete-icon 32x32.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, -1));

        btnubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Text-Edit-icon 32x32.png"))); // NOI18N
        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sign-Refresh-icon 32x32.png"))); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, -1, -1));

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Save-as-icon 32x32.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //untuk membuat tampilan jframe penjualanform penuh layar
        setExtendedState(menuutama.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void cbstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstatusActionPerformed

    }//GEN-LAST:event_cbstatusActionPerformed

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
        String input = txtid.getText();
        if (input.length()>8){
            JOptionPane.showMessageDialog(rootPane,"Jumlah Input ID Order Melebihi Batas");
            txtid.setText("");
        }
    }//GEN-LAST:event_txtidKeyReleased

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="INSERT INTO user VALUES('"+txtid.getText()+"','"
                    +txtnama.getText()+"','"
                    +txtalamat.getText()+"','"
                    +txttlp.getText()+"','"
                    +cbstatus.getSelectedItem()+"','"
                    +txtuser.getText()+"','"
                    +txtpw.getText()+"','"
                    +txtacc.getText()+"')";
            java.sql.Connection con = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();
            
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil");
            
            tampilkan_data();
            kosongkan_form();
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        //Panggil Method KosongkanForm
        kosongkan_form();
        //aktifkan tombol simpan
        btnsimpan.setEnabled(true);
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        try{
            String sql ="UPDATE user SET nama='"+txtnama.getText()
                    +"',alamat ='"+txtalamat.getText()
                    +"',telpon='"+txttlp.getText()
                    +"',status='"+cbstatus.getSelectedItem()
                    +"',username='"+txtuser.getText()
                    +"',password='"+txtpw.getText()
                    +"',akses='"+txtacc.getText()
                    +"'WHERE id_user='"+txtid.getText()+"'";
            java.sql.Connection con = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();
            
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
            
            tampilkan_data();
            kosongkan_form();
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        btnsimpan.setEnabled(true);
        btnubah.setEnabled(false);
        btnhapus.setEnabled(false);
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try{
            String sql="DELETE FROM user WHERE id_user='"+txtid.getText()+"'";
            java.sql.Connection con=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Telah di Hapus...!");
            tampilkan_data();
            kosongkan_form();
            
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        btnsimpan.setEnabled(true);
        btnubah.setEnabled(false);
        btnhapus.setEnabled(false);
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        int pilihan =JOptionPane.showConfirmDialog(null,
                "Apakah Anda ingin keluar dari program ?",
                "Title Keluar:",JOptionPane.YES_NO_OPTION);
        if (pilihan==JOptionPane.YES_OPTION)
            this.dispose();
        else
            txtid.requestFocus();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void tabeluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeluserMouseClicked
        JOptionPane.showMessageDialog(null, 
             "Silahkan data diperbaharui terlebih dahulu \n Lakukan dengan benar \n",
             "Perbaharui Data !",JOptionPane.PLAIN_MESSAGE);
             btnsimpan.setEnabled(false);
             btnubah.setEnabled(true);
             btnhapus.setEnabled(true);
        int baris =tabeluser.rowAtPoint(evt.getPoint());
        String id_user =tabeluser.getValueAt(baris, 1).toString();
        txtid.setText(id_user);
        String nama=tabeluser.getValueAt(baris, 2).toString();
        txtnama.setText(nama);
        String alamat=tabeluser.getValueAt(baris, 3).toString();
        txtalamat.setText(alamat);
        String telpon=tabeluser.getValueAt(baris, 4).toString();
        txttlp.setText(telpon);
        String status=tabeluser.getValueAt(baris, 5).toString();
        cbstatus.setSelectedItem(status);
        String username=tabeluser.getValueAt(baris, 6).toString();
        txtuser.setText(username);
        String password=tabeluser.getValueAt(baris, 7).toString();
        txtpw.setText(password);
        String akses=tabeluser.getValueAt(baris, 8).toString();
        txtacc.setText(akses);
    }//GEN-LAST:event_tabeluserMouseClicked

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        tampilkan_data();
    }//GEN-LAST:event_txtcariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembalikeMainMenu;
    private javax.swing.JButton kembalikeMainMenu1;
    private javax.swing.JTable tabeluser;
    private javax.swing.JTextField txtacc;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpw;
    private javax.swing.JTextField txttlp;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
