/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.sql.Connection;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


import java.io.File;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author user
 */
public class FormlaporanBarangDanUser extends javax.swing.JFrame {

   private void listComboBox(){
       try{
           String sql= "SELECT * FROM user";
           java.sql.Connection conn = (Connection)koneksi.configDB();
           java.sql.Statement stm = conn.createStatement();
           java.sql.ResultSet res = stm.executeQuery(sql);
           
           while(res.next()){
               cbusername.addItem(res.getString("username"));
           }         
           }catch (SQLException e) {
            System.out.println("Error : " +e.getMessage());
       }   
   }
   
   
    public FormlaporanBarangDanUser() {
       initComponents();
       listComboBox();
       this.setResizable(false);
       this.setDefaultCloseOperation(Form_Penjualan.DO_NOTHING_ON_CLOSE);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btncetakbarang = new javax.swing.JButton();
        cetakperharidanusername = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cbusername = new javax.swing.JComboBox<>();
        btncetakuser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kembalikeMainMenu = new javax.swing.JButton();
        btnKembalikeuser = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnkembalikeformbarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncetakbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Distributor-report-icon 32x32.png"))); // NOI18N
        btncetakbarang.setText("Cetak Brang");
        btncetakbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakbarangActionPerformed(evt);
            }
        });
        jPanel2.add(btncetakbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        cetakperharidanusername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Distributor-report-icon 32x32.png"))); // NOI18N
        cetakperharidanusername.setText("Cetak perhari & username");
        cetakperharidanusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakperharidanusernameActionPerformed(evt);
            }
        });
        jPanel2.add(cetakperharidanusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 340, -1));

        jLabel3.setText("Tanggal");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jPanel2.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel4.setText("Username");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        cbusername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ridwan", "leni", "falah", "santi", "nova.r", "puspah", "yoza" }));
        jPanel2.add(cbusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        btncetakuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Distributor-report-icon 32x32.png"))); // NOI18N
        btncetakuser.setText("Cetak user");
        btncetakuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakuserActionPerformed(evt);
            }
        });
        jPanel2.add(btncetakuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 490, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cetak Laporan Barang Dan User");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 360, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/003-newspaper.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        kembalikeMainMenu.setText("Kembali ke Mainmenu");
        kembalikeMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalikeMainMenuActionPerformed(evt);
            }
        });
        jPanel1.add(kembalikeMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        btnKembalikeuser.setText("Kembali ke form user");
        btnKembalikeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembalikeuserActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembalikeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Actions-window-close-icon 24x24.png"))); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        btnkembalikeformbarang.setText("Kembali ke form barang");
        btnkembalikeformbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembalikeformbarangActionPerformed(evt);
            }
        });
        jPanel1.add(btnkembalikeformbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncetakbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakbarangActionPerformed
     JasperReport jr; 
    JasperPrint jp;
    JasperDesign jd;
    try{
        
        //panggil class koneksi
        java.sql.Connection conn =(Connection)koneksi.configDB();
        HashMap parameter=new HashMap();
        
        File report =new File("src/Laporan/LaporanBarang.jrxml");
        jd=JRXmlLoader.load(report);
        jr=JasperCompileManager.compileReport(jd);
        jp=JasperFillManager.fillReport(jr,parameter,conn);
        JasperViewer.viewReport(jp,false);     
    } catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    }//GEN-LAST:event_btncetakbarangActionPerformed

    private void cetakperharidanusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakperharidanusernameActionPerformed
        // TODO add your handling code here:
        JasperReport jr;
        JasperPrint jp;
        JasperDesign jd;
        try{
            java.sql.Connection conn =(Connection)koneksi.configDB();
            HashMap parameter=new HashMap();
            parameter.put("namauser", cbusername.getSelectedItem());
            File report = new File("src/Laporan/perhariuser.jrxml");
            jd=JRXmlLoader.load(report);
            jr=JasperCompileManager.compileReport(jd);
            jp=JasperFillManager.fillReport(jr,parameter,conn);
            JasperViewer.viewReport(jp,false);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cetakperharidanusernameActionPerformed

    private void btncetakuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakuserActionPerformed
     JasperReport jr; 
    JasperPrint jp;
    JasperDesign jd;
    try{
        
        //panggil class koneksi
        java.sql.Connection conn =(Connection)koneksi.configDB();
        HashMap parameter=new HashMap();
        
        File report =new File("src/Laporan/LaporanUser.jrxml");
        jd=JRXmlLoader.load(report);
        jr=JasperCompileManager.compileReport(jd);
        jp=JasperFillManager.fillReport(jr,parameter,conn);
        JasperViewer.viewReport(jp,false);     
    } catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    }//GEN-LAST:event_btncetakuserActionPerformed

    private void kembalikeMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalikeMainMenuActionPerformed
  new menuutama().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_kembalikeMainMenuActionPerformed

    private void btnKembalikeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembalikeuserActionPerformed
      new Form_User().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnKembalikeuserActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnkembalikeformbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembalikeformbarangActionPerformed
     new Form_Barang().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnkembalikeformbarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormlaporanBarangDanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormlaporanBarangDanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormlaporanBarangDanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormlaporanBarangDanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormlaporanBarangDanUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembalikeuser;
    private javax.swing.JButton btncetakbarang;
    private javax.swing.JButton btncetakuser;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnkembalikeformbarang;
    private javax.swing.JComboBox<String> cbusername;
    private javax.swing.JButton cetakperharidanusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kembalikeMainMenu;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables
}
