/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;
import javax.swing.JOptionPane;
public class menuutama extends javax.swing.JFrame {

    /**
     * Creates new form menuutama
     */
    public menuutama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btndatauser = new javax.swing.JButton();
        btndatabarang = new javax.swing.JButton();
        btndatatransaksi = new javax.swing.JButton();
        btnpenjualan = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jhome = new javax.swing.JMenu();
        mlogin = new javax.swing.JMenuItem();
        mlogout = new javax.swing.JMenuItem();
        jmaster = new javax.swing.JMenu();
        mdatauser = new javax.swing.JMenuItem();
        mdatabarang = new javax.swing.JMenuItem();
        mdatatransaksi = new javax.swing.JMenuItem();
        jpenjualan = new javax.swing.JMenu();
        mdatatransaksipenjualan = new javax.swing.JMenuItem();
        jlaporan = new javax.swing.JMenu();
        mlaporanperpriode = new javax.swing.JMenuItem();
        mlaporanuser = new javax.swing.JMenuItem();
        mlaporanbarang = new javax.swing.JMenuItem();
        mlaporanperhariuser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MINIMARKET MURAH BANGET");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Jl. Purwosari Perum Pandau Kencana, Kec. Siak Hulu, Kab. Kampar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/supermarket (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 530, 570));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Menu Utama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        btndatauser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user.png"))); // NOI18N
        btndatauser.setText("Data User");
        btndatauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatauserActionPerformed(evt);
            }
        });
        getContentPane().add(btndatauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, -1));

        btndatabarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/002-groceries.png"))); // NOI18N
        btndatabarang.setText("Data Barang");
        btndatabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatabarangActionPerformed(evt);
            }
        });
        getContentPane().add(btndatabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, -1));

        btndatatransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/001-point-of-service.png"))); // NOI18N
        btndatatransaksi.setText("Data Transaksi");
        btndatatransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatatransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btndatatransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        btnpenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/005-cashier-1.png"))); // NOI18N
        btnpenjualan.setText("Penjualan");
        btnpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpenjualanActionPerformed(evt);
            }
        });
        getContentPane().add(btnpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 170, -1));

        btnlaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/001-money.png"))); // NOI18N
        btnlaporan.setText("Laporan");
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 170, -1));

        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Actions-window-close-icon 32x32.png"))); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 170, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/User-Administrator-Blue-icon 32x32.png"))); // NOI18N
        jhome.setText("Home");

        mlogin.setText("LOGIN");
        mlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mloginActionPerformed(evt);
            }
        });
        jhome.add(mlogin);

        mlogout.setText("LOGOUT");
        mlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlogoutActionPerformed(evt);
            }
        });
        jhome.add(mlogout);

        jMenuBar1.add(jhome);

        jmaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Misc-New-Database-icon 32x32.png"))); // NOI18N
        jmaster.setText("Master");

        mdatauser.setText("Data User");
        mdatauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatauserActionPerformed(evt);
            }
        });
        jmaster.add(mdatauser);

        mdatabarang.setText("Data Barang");
        mdatabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatabarangActionPerformed(evt);
            }
        });
        jmaster.add(mdatabarang);

        mdatatransaksi.setText("Data Transaksi");
        mdatatransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatatransaksiActionPerformed(evt);
            }
        });
        jmaster.add(mdatatransaksi);

        jMenuBar1.add(jmaster);

        jpenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/data-management-icon 32x32.png"))); // NOI18N
        jpenjualan.setText("Penjualan");

        mdatatransaksipenjualan.setText("Data Transaksi Penjualan");
        mdatatransaksipenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatatransaksipenjualanActionPerformed(evt);
            }
        });
        jpenjualan.add(mdatatransaksipenjualan);

        jMenuBar1.add(jpenjualan);

        jlaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Distributor-report-icon 32x32.png"))); // NOI18N
        jlaporan.setText("Laporan");

        mlaporanperpriode.setText("Laporan Perpriode");
        mlaporanperpriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlaporanperpriodeActionPerformed(evt);
            }
        });
        jlaporan.add(mlaporanperpriode);

        mlaporanuser.setText("Laporan User");
        mlaporanuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlaporanuserActionPerformed(evt);
            }
        });
        jlaporan.add(mlaporanuser);

        mlaporanbarang.setText("Laporan Barang");
        mlaporanbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlaporanbarangActionPerformed(evt);
            }
        });
        jlaporan.add(mlaporanbarang);

        mlaporanperhariuser.setText("Laporan Perhari User");
        mlaporanperhariuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlaporanperhariuserActionPerformed(evt);
            }
        });
        jlaporan.add(mlaporanperhariuser);

        jMenuBar1.add(jlaporan);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mloginActionPerformed
        // TODO add your handling code here:
        jabatan jabatan = new jabatan();
        jabatan.setVisible(true);
        dispose();
    }//GEN-LAST:event_mloginActionPerformed

    private void mlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlogoutActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(null, "Keluar dari aplikasi",
            "Konfirmasi ulang",JOptionPane.OK_CANCEL_OPTION);
        if(pilih == JOptionPane.OK_OPTION){
            System.exit(0);
        }else{
            JOptionPane.getRootFrame();
        }
    }//GEN-LAST:event_mlogoutActionPerformed

    private void mdatauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatauserActionPerformed
        // TODO add your handling code here:
        new Form_User().setVisible(true);
        mdatauser.setEnabled(true);
    }//GEN-LAST:event_mdatauserActionPerformed

    private void mdatabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatabarangActionPerformed
        // TODO add your handling code here:
        new Form_Barang().setVisible(true);
        btndatabarang.setEnabled(true);
    }//GEN-LAST:event_mdatabarangActionPerformed

    private void mdatatransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatatransaksiActionPerformed
        // TODO add your handling code here:
        new Form_DataTransaksi().setVisible(true);
        mdatatransaksi.setEnabled(true);
    }//GEN-LAST:event_mdatatransaksiActionPerformed

    private void mdatatransaksipenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatatransaksipenjualanActionPerformed
        // TODO add your handling code here:
        new Form_DataTransaksi().setVisible(true);
        mdatatransaksipenjualan.setEnabled(true);
    }//GEN-LAST:event_mdatatransaksipenjualanActionPerformed

    private void mlaporanperpriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlaporanperpriodeActionPerformed
        // TODO add your handling code here:
        new FormCetaklaporanperperiode().setVisible(true);
        mlaporanperpriode.setEnabled(true);
    }//GEN-LAST:event_mlaporanperpriodeActionPerformed

    private void mlaporanuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlaporanuserActionPerformed
        // TODO add your handling code here:
        new FormlaporanBarangDanUser().setVisible(true);
        mlaporanuser.setEnabled(true);
    }//GEN-LAST:event_mlaporanuserActionPerformed

    private void mlaporanbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlaporanbarangActionPerformed
        // TODO add your handling code here:
        new FormlaporanBarangDanUser().setVisible(true);
        mlaporanbarang.setEnabled(false);
        dispose();
    }//GEN-LAST:event_mlaporanbarangActionPerformed

    private void mlaporanperhariuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlaporanperhariuserActionPerformed
        // TODO add your handling code here:
        new FormCetaklaporanperperiode().setVisible(true);
        mlaporanperhariuser.setEnabled(true);
    }//GEN-LAST:event_mlaporanperhariuserActionPerformed

    private void btndatauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatauserActionPerformed
        new Form_User().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btndatauserActionPerformed

    private void btndatabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatabarangActionPerformed
        new Form_Barang().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btndatabarangActionPerformed

    private void btndatatransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatatransaksiActionPerformed
        new Form_DataTransaksi().setVisible(true);
     this.dispose();
      
    }//GEN-LAST:event_btndatatransaksiActionPerformed

    private void btnpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpenjualanActionPerformed
         new Form_Penjualan().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnpenjualanActionPerformed

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
        new FormlaporanBarangDanUser().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnlaporanActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(null,
            "Apakah anda ingin keluar dari program?",
            "Exit ",JOptionPane.YES_NO_OPTION);
        if (pilihan ==JOptionPane.YES_OPTION)
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btndatabarang;
    public javax.swing.JButton btndatatransaksi;
    public javax.swing.JButton btndatauser;
    public javax.swing.JButton btnlaporan;
    public javax.swing.JButton btnlogout;
    public javax.swing.JButton btnpenjualan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu jhome;
    public javax.swing.JMenu jlaporan;
    public javax.swing.JMenu jmaster;
    public javax.swing.JMenu jpenjualan;
    public javax.swing.JMenuItem mdatabarang;
    public javax.swing.JMenuItem mdatatransaksi;
    public javax.swing.JMenuItem mdatatransaksipenjualan;
    public javax.swing.JMenuItem mdatauser;
    public javax.swing.JMenuItem mlaporanbarang;
    public javax.swing.JMenuItem mlaporanperhariuser;
    public javax.swing.JMenuItem mlaporanperpriode;
    public javax.swing.JMenuItem mlaporanuser;
    public javax.swing.JMenuItem mlogin;
    public javax.swing.JMenuItem mlogout;
    // End of variables declaration//GEN-END:variables
}
